# Exploratory Data Analysis (EDA)

## Step 1: Importing Libraries

We begin the EDA process by importing the required library:

- **pandas** → Used for data manipulation and analysis.
- **numpy** → Used for handling numerical operations and missing values.

These libraries help in cleaning, transforming, and analyzing structured data efficiently.

## Step 2: Loading the Dataset

The dataset is loaded using `pd.read_excel()`.

This converts the Excel file into a Pandas DataFrame, allowing structured data analysis.

In [1]:
import pandas as pd

emp = pd.read_excel(r"/Users/afnanshaikh/Downloads/RawData.xlsx")
print(pd.__version__)
emp

3.0.0

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

## Step 3: Initial Data Inspection

To understand the dataset structure, we performed:

- `head()` → View first 5 rows
- `tail()` → View last 5 rows
- `info()` → Summary of dataset
- `dtypes` → Data types of each column
- `describe()` → Statistical summary of numerical columns

This step helps in understanding:
- Number of rows and columns
- Data types
- Missing values
- Distribution of numerical features

In [2]:
id(emp)

5278808256

In [3]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [4]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [5]:
emp.dtypes

Name        str
Domain      str
Age         str
Location    str
Salary      str
Exp         str
dtype: object

In [6]:
emp.describe()

        Name         Domain       Age Location  Salary Exp
count      6              6         4        4       6   5
unique     6              6         4        4       6   5
top     Mike  Datascience#$  34 years   Mumbai  5^00#0  2+
freq       1              1         1        1       1   1

In [7]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       4 non-null      str
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       5 non-null      str
dtypes: str(6)
memory usage: 619.0 bytes

## Step 4: Handling Missing Values

We used:

- `isnull()` → Detect missing values
- `isnull().sum()` → Count missing values column-wise

This helps identify incomplete data that must be cleaned before analysis.

In [8]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [9]:
emp.isnull().sum()     # count of null values....

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

#  Data Cleaning or Data Cleansing.....

## Step 5: Cleaning Text Data

Special characters were removed from text columns such as:

- Name
- Domain
- Salary
- Experience
- Age

We used `str.replace()` with regular expressions to remove:

- Non-word characters (`\W`)
- Non-digit characters (`\D`)

This ensures consistent and clean textual data.

In [10]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [11]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: str

In [12]:
emp['Name'] = emp['Name'].str.replace(r'\W', '', regex = True)   # Non Word Character

In [13]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: str

In [14]:
emp.dtypes

Name        str
Domain      str
Age         str
Location    str
Salary      str
Exp         str
dtype: object

In [15]:
emp['Domain'] = emp['Domain'].str.replace(r'\W', '', regex = True)
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: str

In [16]:
emp.head()

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year

## Step 6: Data Type Conversion

Some columns were stored as strings but should be numeric.

We converted:
- Salary → int
- Experience → float → int
- Age → float → int

Using `astype()` ensures correct data types for analysis and calculations.

In [17]:
emp['Salary'] = emp['Salary'].str.replace(r'\W', '', regex = True)

emp['Salary']

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: str

In [18]:
emp['Salary'] = emp['Salary'].astype(int)
emp['Salary'].dtypes

dtype('int64')

In [19]:
emp['Exp'] = emp['Exp'].str.replace(r'\D', '', regex= True)
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: str

In [20]:
emp['Exp'].isnull().sum()

np.int64(1)

In [21]:
emp['Exp'] = emp['Exp'].astype('float')

## Step 7: Filling Missing Numerical Values

For numerical columns such as:

- Experience
- Age

Missing values were replaced with the column mean using:

`replace(np.nan, column.mean())`

This prevents data loss and maintains statistical balance.

In [22]:
import numpy as np
emp['Exp'] = emp['Exp'].replace(np.nan, emp['Exp'].mean())
emp

    Name       Domain       Age   Location  Salary   Exp
0   Mike  Datascience  34 years     Mumbai    5000   2.0
1  Teddy      Testing    45' yr  Bangalore   10000   3.0
2   Umar  Dataanalyst       NaN        NaN   15000   4.0
3   Jane    Analytics       NaN   Hyderbad   20000   4.8
4  Uttam   Statistics     67-yr        NaN   30000   5.0
5    Kim          NLP      55yr      Delhi   60000  10.0

In [23]:
emp['Exp'] = emp['Exp'].astype('int')

emp

    Name       Domain       Age   Location  Salary  Exp
0   Mike  Datascience  34 years     Mumbai    5000    2
1  Teddy      Testing    45' yr  Bangalore   10000    3
2   Umar  Dataanalyst       NaN        NaN   15000    4
3   Jane    Analytics       NaN   Hyderbad   20000    4
4  Uttam   Statistics     67-yr        NaN   30000    5
5    Kim          NLP      55yr      Delhi   60000   10

In [24]:
emp['Age'] = emp['Age'].str.replace(r'\D', '', regex = True)

emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: str

In [25]:
emp['Age'] = emp['Age'].astype('float')
emp['Age'].dtype

dtype('float64')

In [26]:
emp["Age"] = emp['Age'].replace(np.nan, emp['Age'].mean())
emp

    Name       Domain    Age   Location  Salary  Exp
0   Mike  Datascience  34.00     Mumbai    5000    2
1  Teddy      Testing  45.00  Bangalore   10000    3
2   Umar  Dataanalyst  50.25        NaN   15000    4
3   Jane    Analytics  50.25   Hyderbad   20000    4
4  Uttam   Statistics  67.00        NaN   30000    5
5    Kim          NLP  55.00      Delhi   60000   10

In [27]:
emp['Age'] = emp['Age'].astype('int')
emp

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai    5000    2
1  Teddy      Testing   45  Bangalore   10000    3
2   Umar  Dataanalyst   50        NaN   15000    4
3   Jane    Analytics   50   Hyderbad   20000    4
4  Uttam   Statistics   67        NaN   30000    5
5    Kim          NLP   55      Delhi   60000   10

## Step 8: Standardizing Categorical Data

Some categorical values were inconsistent, such as:

- "Datascience" → "Data Science"
- "Dataanalyst" → "Data Analyst"

We replaced them using `.replace()` to maintain uniform category naming.

This improves grouping and analysis accuracy.

In [28]:
emp['Domain'] = emp['Domain'].replace('Datascience', 'Data Science').replace('Dataanalyst', 'Data Analyst')
emp

    Name        Domain  Age   Location  Salary  Exp
0   Mike  Data Science   34     Mumbai    5000    2
1  Teddy       Testing   45  Bangalore   10000    3
2   Umar  Data Analyst   50        NaN   15000    4
3   Jane     Analytics   50   Hyderbad   20000    4
4  Uttam    Statistics   67        NaN   30000    5
5    Kim           NLP   55      Delhi   60000   10

## Step 9: Filling Missing Categorical Values

For the 'Location' column:

Missing values were replaced with "Unknown".

This ensures:
- No null values remain
- Categorical consistency
- Better grouping during analysis

In [29]:
print(emp['Location'].isnull().sum())

2

In [30]:
emp['Location'] = emp['Location'].replace(np.nan, 'Unknown')

emp

    Name        Domain  Age   Location  Salary  Exp
0   Mike  Data Science   34     Mumbai    5000    2
1  Teddy       Testing   45  Bangalore   10000    3
2   Umar  Data Analyst   50    Unknown   15000    4
3   Jane     Analytics   50   Hyderbad   20000    4
4  Uttam    Statistics   67    Unknown   30000    5
5    Kim           NLP   55      Delhi   60000   10